
server:
  port:

spring:
  profiles:
    include: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:

  servlet:
    multipart:
      max-file-size:
      max-request-size:

  # AWS Account Credentials

cloud:
  aws:
    credentials:
      access-key:
      secret-key:

    # AWS S3 bucket Info
    s3:
      bucket:
    region:
      static:
    stack:
      auto:

jwt:
  secret:
    access:
    refresh:
  time:
    access:
    refresh:

durunubi:
  secret:
